version: 2

project_name: mbzr

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/andpalmier/mbzr/cmd.Version={{.Version}} -X github.com/andpalmier/mbzr/cmd.Commit={{.Commit}} -X github.com/andpalmier/mbzr/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: andpalmier
      name: homebrew-tap
    
    # Template for the url which is determined by the given Token (github_token or gitlab_token)
    url_template: "https://github.com/andpalmier/mbzr/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # The project name and description for the formula.
    name: mbzr
    description: "MalwareBazaar CLI Client"
    homepage: "https://github.com/andpalmier/mbzr"

    # License
    license: "AGPL-3.0"

    # Folder inside the repository to put the formula.
    directory: Formula

    # Dependencies
    dependencies:
      - name: git
    
    # Custom install
    install: |
      bin.install "mbzr"
      
      # Install bash completion
      output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "bash")
      (bash_completion/"mbzr").write output

      # Install zsh completion
      output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "zsh")
      (zsh_completion/"_mbzr").write output

      # Install fish completion
      output = Utils.safe_popen_read("#{bin}/mbzr", "completion", "fish")
      (fish_completion/"mbzr.fish").write output

dockers:
  - image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    extra_files:
      - go.mod
      - Makefile
      - main.go
      - api/
      - cmd/
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

  - image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    extra_files:
      - go.mod
      - Makefile
      - main.go
      - api/
      - cmd/
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/andpalmier/mbzr:{{ .Tag }}"
    image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-amd64"
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-arm64"
  
  - name_template: "ghcr.io/andpalmier/mbzr:latest"
    image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-amd64"
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-arm64"
  
  - name_template: "ghcr.io/andpalmier/mbzr:v{{ .Major }}"
    image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-amd64"
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/andpalmier/mbzr:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-amd64"
      - "ghcr.io/andpalmier/mbzr:{{ .Tag }}-arm64"
